# Generated by Django 2.2.3 on 2019-07-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.IntegerField(default=1)),
                ('django', models.IntegerField(default=1)),
                ('javascript', models.IntegerField(default=1)),
                ('cpp', models.IntegerField(default=1)),
                ('english', models.IntegerField(default=1)),
                ('comunication', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='candidates.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('skils', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='candidates.Rates')),
            ],
        ),
    ]
