# Generated by Django 2.2.3 on 2019-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='javascript',
        ),
        migrations.AddField(
            model_name='skills',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='skils',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='comunication',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='cpp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='django',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
